name: Terraform CI-CD

on:
  push:
    branches:
      - feature
      - main

permissions:
  contents: read

env:
  TF_WORKING_DIR: ./Enviroment/Devlopment

jobs:

  # ==================================================
  # TERRAFORM PLAN
  # Runs only when code is pushed to feature branch
  # ==================================================

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/feature'

    steps:

      # Checkout
      - name: Checkout Code
        uses: actions/checkout@v4

      # Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      # Azure Login
      # App Registration + Client Secret
      - name: Azure Login
        uses: azure/login@v2
        with:
        auth-type: SERVICE_PRINCIPAL
          creds: |
            {
              "clientId": "7a8e96d0-1e46-4e44-8553-7598eef4f67e",
              "clientSecret": "PR58Q~cL6NhdMfvNmgSm.qm8OX6qCQy~7cP47cy0",
              "subscriptionId": "2eeb0869-d474-4f94-a0b0-fb6a5d23d142",
              "tenantId": "093e9319-5648-4618-8c7d-f585fb2ed3f9"
            }

      # Terraform Init
      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      # Terraform Format
      - name: Terraform Format Check
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -check -recursive

      # Terraform Validate
      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      # Terraform Plan
      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan


  # ==================================================
  # TERRAFORM APPLY
  # Runs only when code is pushed to main branch
  # ==================================================

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    # Manual approval before Apply
    environment:
      name: production

    steps:

      # Checkout
      - name: Checkout Code
        uses: actions/checkout@v4

      # Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      # Azure Login
      # App Registration + Client Secret
      - name: Azure Login
        uses: azure/login@v2
        with:
        auth-type: SERVICE_PRINCIPAL
          creds: |
            {
              "clientId": "7a8e96d0-1e46-4e44-8553-7598eef4f67e",
              "clientSecret": "PR58Q~cL6NhdMfvNmgSm.qm8OX6qCQy~7cP47cy0",
              "subscriptionId": "2eeb0869-d474-4f94-a0b0-fb6a5d23d142",
              "tenantId": "093e9319-5648-4618-8c7d-f585fb2ed3f9"
            }

      # Terraform Init
      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      # Terraform Apply
      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve