name: Terraform CI-CD

on:
  push:
    branches:
      - feature
      - main

  pull_request:
    branches:
      - main

env:
  TF_WORKING_DIR: ./Action-Trigger/Enviroment/Devlopment

permissions:
  contents: read

jobs:

  # ==========================================
  # PLAN
  # Feature push  -> Plan
  # PR to main    -> Plan
  # Main push     -> Plan
  # ==========================================

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: "7a8e96d0-1e46-4e44-8553-7598eef4f67e"
          tenant-id: "093e9319-5648-4618-8c7d-f585fb2ed3f9"
          subscription-id: "2eeb0869-d474-4f94-a0b0-fb6a5d23d142"

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Format Check
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan


  # ==========================================
  # APPLY
  # ONLY MAIN BRANCH PUSH
  # ==========================================

  terraform-apply:
    name: Terraform Apply

    needs: terraform-plan

    if: >
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    environment:
      name: production

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: "7a8e96d0-1e46-4e44-8553-7598eef4f67e"
          tenant-id: "093e9319-5648-4618-8c7d-f585fb2ed3f9"
          subscription-id: "2eeb0869-d474-4f94-a0b0-fb6a5d23d142"

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve